apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: n8jz2rk1l-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/n8jz2rk1l-dotnet-basic-gitops